// this file is automatically generated by git-describe-version.ts script, please don't edit and git commit
export const versions = {
  version: '0.0.1',
  revision: '8f8ef7c',
  branch: 'master',
};
